# Generated by Django 3.2.9 on 2021-12-24 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('theme', models.CharField(max_length=200)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abacus.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abacus.problem')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='problem',
            field=models.ManyToManyField(through='abacus.ProblemInclusion', to='abacus.Problem'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.FloatField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abacus.problem')),
            ],
        ),
    ]
