# Generated by Django 3.2.9 on 2021-12-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abacus', '0002_contest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_number',
            new_name='answer_value',
        ),
        migrations.CreateModel(
            name='ProblemInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('theme', models.CharField(max_length=200)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abacus.contest')),
                ('problems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abacus.problem')),
            ],
        ),
        migrations.AlterField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(through='abacus.ProblemInclusion', to='abacus.Problem'),
        ),
    ]
